// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dojob

import (
	"gf-vue3-admin/api/dojob"
	"gf-vue3-admin/internal/service/register"
)

func init() {
	register.Register("dojob", NewV1())
}

type ControllerV1 struct{}

func NewV1() dojob.IDojobV1 {
	return &ControllerV1{}
}
