// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package menu

import (
	"gf-vue3-admin/api/menu"
	"gf-vue3-admin/internal/service/register"
)

func init() {
	register.Register("menu", NewV1())
}

type ControllerV1 struct{}

func NewV1() menu.IMenuV1 {
	return &ControllerV1{}
}
