// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package utility

import (
	"gf-vue3-admin/api/utility"
	"gf-vue3-admin/internal/service/register"
)

func init() {
	register.Register("utility", NewV1())
}

type ControllerV1 struct{}

func NewV1() utility.IUtilityV1 {
	return &ControllerV1{}
}
