// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-vue3-admin/internal/dao/internal"
)

// internalSshDao is internal type for wrapping internal DAO implements.
type internalSshDao = *internal.SshDao

// sshDao is the data access object for table ssh.
// You can define custom methods on it to extend its functionality as you wish.
type sshDao struct {
	internalSshDao
}

var (
	// Ssh is globally public accessible object for table ssh operations.
	Ssh = sshDao{
		internal.NewSshDao(),
	}
)

// Fill with you ideas below.
